version: '3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /path/to/sonarr/data:/config
    - /path/to/tvseries:/tv
    - /path/to/downloadclient-downloads:/downloads
    ports:
    - 8989:8989
    restart: unless-stopped
