# ======================
# Global Configuration
# ======================
proxmox:
  host: "10.11.30.4"
  target_node: "homelab"

template:
  ubuntu:
    name: "ubuntu-2404-cloudinit-template"
    image: "noble-server-cloudimg-amd64.img"
    vmid: 9000
    datasource_id: "dockervms"
    disk: 20
    memory: 1024
    user: "homelab"
    ssh_key: "/home/pi/.ssh/id_rsa_homelab.pub"
    tags: ["template", "ubuntu"]

# ======================
# VM Configuration
# ======================
hosts:
  - name: vm-networking
    cores: 2
    memory: 4096   
    disk: 32
    ip: 10.11.30.6/24
    gateway: 10.11.30.1
    template: 9000

  - name: vm-databases
    cores: 4
    memory: 8192 
    disk: 64
    ip: 10.11.30.7/24
    gateway: 10.11.30.1
    template: 9000
