# ======================
# VM Configuration
# ======================
vms:
  postgres:
    name: "postgres_vm"
    ip: "10.11.30.50"
    ssh_user: "admin"
    memory: "2G"
    disk_size: "20G"
    base_data_dir: "/opt/data"

  wikijs:
    name: "wikijs_vm"
    ip: "10.11.30.51"
    ssh_user: "admin"
    memory: "2G"
    disk_size: "10G"
    base_data_dir: "/opt/data"

# ======================
# Docker Configuration
# ======================

docker:
  audiobookshelf:
    vm: 'postgres_vm'
    data_dir: "paperless/data"
    media_dir: "paperless/media"
    port: 13377

  paperless:
    vm: 'postgres_vm'
    data_dir: "paperless/data"
    media_dir: "paperless/media"
    port: 8000

# ======================
# Network Configuration
# ======================
network:
  main_vlan: "10.11.10.0/24"
  server_vlan: "10.11.30.0/24"
