---
- name: Create venv and run config generator
  hosts: localhost
  gather_facts: no
  vars:
    terraform_dir: "{{ playbook_dir }}/../terraform_output"

  tasks:

    - name: Run terraform init in terraform_output directory
      command: terraform init
      args:
        chdir: "{{ terraform_dir }}"

    - name: Destroy existing Terraform resources
      command: terraform destroy -auto-approve
      args:
        chdir: "{{ terraform_dir }}"

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: "{{ terraform_dir }}"