- hosts: all
  gather_facts: no
  tasks:

    - name: Remove old known_hosts backup if it exists
      delegate_to: localhost
      file:
        path: "~/.ssh/known_hosts.old"
        state: absent

    - name: Remove host key from known_hosts by IP and port
      delegate_to: localhost
      shell: |
        ssh-keygen -R "{{ ansible_host | default(inventory_hostname) }}"
        ssh-keygen -R "[{{ ansible_host | default(inventory_hostname) }}]:{{ ansible_port | default(22) }}"
      ignore_errors: yes

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - _provision
