- hosts: all
  gather_facts: no
  tasks:

    - name: Attempt to update known_hosts safely
      block:

        - name: Wait until host is reachable on SSH
          wait_for:
            port: "{{ ansible_port | default(22) }}"
            host: "{{ ansible_host | default(inventory_hostname) }}"
            timeout: 30
          delegate_to: localhost

        - name: Remove all existing SSH host keys from known_hosts
          local_action: >
            shell >
              ssh-keygen -R "{{ ansible_host | default(inventory_hostname) }}" || true &&
              ssh-keygen -R "[{{ ansible_host | default(inventory_hostname) }}]:{{ ansible_port | default(22) }}" || true
          delegate_to: localhost

        - name: Fetch current SSH host key into temp file
          local_action: >
            shell ssh-keyscan -p {{ ansible_port | default(22) }} -H {{ ansible_host | default(inventory_hostname) }}
          register: scanned_key
          delegate_to: localhost

        - name: Write new host key, replacing known_hosts entry
          copy:
            content: "{{ scanned_key.stdout }}"
            dest: "~/.ssh/known_hosts"
            mode: "0600"
          delegate_to: localhost

      rescue:
        - name: Log warning if host key update fails
          debug:
            msg: "Skipping host key update for {{ inventory_hostname }} because it is not reachable or resolvable."

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - _provision
