- hosts: all
  gather_facts: no
  tasks:
    - name: Remove old SSH host key from known_hosts
      local_action: >
        shell ssh-keygen -R "[{{ inventory_hostname }}]:{{ ansible_port }}"
      delegate_to: localhost
      run_once: false

    - name: Add current SSH host key to known_hosts
      local_action: >
        shell ssh-keyscan -p {{ ansible_port }} -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
      delegate_to: localhost
      run_once: false

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - provision

